#+TITLE: Francis Murillo's Emacs configuration
#+AUTHOR: Frncis Murillo
#+OPTIONS: toc:4 h:4

* Introduction
** If I Forget
   No words can describe my awe with Emacs and continue to do so. A text editor with a lisp interpreter, it's concept is so simple and sublime. What joy.

   I remember starting Emacs seriously at around August of 2015. Before then, I picked it up lightly and thought(not use) about it; but what really drove me to use it is.
   - Growth :: I was using an IDE before and somebody told me that GUIs change but the shell remains the same. I found myself over time exploring keyboard shortcuts, better terminals and Emacs(or maybe vi).
   - Lightweight :: I had a crappy laptop that always needed to be plugged, had a lot dead pixels, and closes when it overheats; I needed something that would work with what I had.
   - Linux :: Moving from Windows to Linux forced me to reevaluate the software I used. Adopting a new philosophy and OS pushed me in the right direction

   Whatever the reason might have been. I just want to say I'm a happy Emacs user and I find comfort and joy in hearing other people talk and share about it.
** About My Configuration
   I use org-babel as my configuration file once I heard you can do so. Splitting the configuration to multiple files was the plan but the way it weaves nicely to documentation immediately drew me in.

   You can load this with =(org-babel-load-file "/path/to/file")= if you need to reload any changes.

   This is my =init.el= to allow org-babel to read from it. My only problem is having the static org-mode in the elisp folder, you have to copy the elisp folder as well to make the configuration work as is.

   #+BEGIN_SRC emacs-lisp :tangle no
     (unless (>= emacs-major-version 24)
       (message "This config works only for Emacs version 24 and higher")
       (kill-emacs))

     ;; Helper functions
     (defun string/ends-with (s ending)
       "Return non-nil if string S ends with ENDING."
       (cond ((>= (length s) (length ending))
              (let ((elength (length ending)))
                (string= (substring s (- 0 elength)) ending)))
             (t nil)))

     (require 'cl)
     (setq load-path
           (remove-if
            (lambda (text) (string/ends-with text "org"))
            load-path))

     ;; customize loading the packages
     (package-initialize t)

     ;; Modify the hard dependencies
     ;; org-mode used to be here

     ;; Load the rest of the packages
     (package-initialize nil)

     ;; Configuration bootstrapping
     ;; use-package is fundamental to this configuration
     (unless (package-installed-p 'use-package)
       (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))
       (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))
       (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
       (add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/"))

       (package-refresh-contents)
       (package-install 'use-package)
       (require 'use-package)

       (use-package org
         :ensure t)
       (use-package org-plus-contrib
         :ensure t)

       ;; Weird dependency
       (use-package dash
         :ensure t)
       (kill-emacs))

     ;; This part assumes ony org-babel-load-file is available
     (setq package-enable-at-startup nil)
     (org-babel-load-file
      (expand-file-name "config.org" user-emacs-directory))
   #+END_SRC

   Or with an function instead

   #+BEGIN_SRC emacs-lisp
     (defun fn/reload-config ()
     (interactive)
     (org-babel-load-file
      (expand-file-name "config.org" user-emacs-directory)))
   #+END_SRC

   Also the code formatting needs to be uniform within the code blocks

   #+BEGIN_SRC emacs-lisp
     (setq org-src-tab-acts-natively t)
   #+END_SRC

* Configuration
** Personal Options
   Just some things that relate to me

   #+BEGIN_SRC emacs-lisp
     (setq
      user-full-name "Francis Murillo"
      user-mail-address "francisavmurillo@gmail.com")
   #+END_SRC

   And load some secret configuration

   #+BEGIN_SRC emacs-lisp
     (load "secret" t)
   #+END_SRC
** Installation Option
   Any configuration option I use to build Emacs

   #+BEGIN_SRC sh
     ls -al
   #+END_SRC

** Package Sources
   Add package sources if not present and reload, this should have been added in the =init.el= but checked here again for completion.

   #+BEGIN_SRC emacs-lisp
     (unless (assoc-default "melpa" package-archives)
       (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))
       (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))
       (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
       (add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/")))
   #+END_SRC

** Prepare Bootstrap
   Initialize everything needed to configure the rest. The two major packages =use-package= and =org= have been loaded in the =init.el= file; here are the extra bootstrapping option

   #+BEGIN_SRC emacs-lisp
     (require 'use-package)
     (setq use-package-verbose t)
   #+END_SRC

** General Configuration
*** Startup
    Startup options to stop annoying you

    #+BEGIN_SRC emacs-lisp
      (setq inhibit-startup-screen t)
      (setq initial-scratch-message nil)
    #+END_SRC
*** Environment
    Some environment configuration

    #+BEGIN_SRC emacs-lisp
      (set-language-environment "UTF-8")
    #+END_SRC

    How about changing some options

    #+BEGIN_SRC emacs-lisp
      (fset 'yes-or-no-p 'y-or-n-p)
    #+END_SRC

*** Backups
    Backups are good, just annoying when things are good

   #+BEGIN_SRC emacs-lisp
     (setq backup-directory-alist '(("." . "~/.emacs.d/backups")))
   #+END_SRC

   Version control is good, like wise.

   #+BEGIN_SRC emacs-lisp
     (setq delete-old-versions -1)
     (setq version-conrol t)
     (setq backup-by-copying t)
     (setq vc-make-backup-files t)
     ;; FIXME: Hard coded path?
     (setq auto-save-file-name-transforms '((".*" "~/.emacs.d/auto-save-list/" t)))
   #+END_SRC

*** History
    Save minibuffer history

    #+BEGIN_SRC emacs-lisp
      (savehist-mode 1)

      (setq savehist-file (expand-file-name "savehist" user-emacs-directory))
      (setq history-length t)
      (setq history-delete-duplicates t)
      (setq savehist-save-minibuffer-history 1)
      (setq savehist-additional-variables
        '(kill-ring
          search-ring
          regexp-search-ring))
    #+END_SRC

*** Window
    Window/Frame configuration. I prefer no clutter in my screen so I disable majority of the niceties.

    #+BEGIN_SRC emacs-lisp
      (tooltip-mode -1)
      (tool-bar-mode -1)
      (menu-bar-mode -1)
      (scroll-bar-mode -1)
    #+END_SRC
*** Buffer
    Some buffer configurations

    #+BEGIN_SRC emacs-lisp
      (global-whitespace-mode t)
      (global-auto-revert-mode t)
      (global-visual-line-mode t)

      (global-hl-line-mode t)
    #+END_SRC

*** Font
    I like fixed font specially DejaVu Mono

    #+BEGIN_SRC emacs-lisp
      (set-frame-font "DejaVu Sans Mono-6" t t)
    #+END_SRC

*** Theme
    Emacs theme for me. I prefer the default tsdh-dark since it's default doesn't ask too much.

    If there is no window system or in a terminal,
    #+BEGIN_SRC emacs-lisp
      (unless (window-system) (load-theme 'tsdh-light))
    #+END_SRC

    #+BEGIN_SRC emacs-lisp
      (when (window-system) (load-theme 'tsdh-dark))
    #+END_SRC

*** Programming
    Some programming configuration that make sense

    #+BEGIN_SRC emacs-lisp
      (global-set-key (kbd "RET") 'newline-and-indent)

      (setq-default indent-tabs-mode nil)
      (show-paren-mode t)
      (add-hook 'before-save-hook 'delete-trailing-whitespace)
    #+END_SRC

** Builtin Modes
*** winner
    You got to have those window configuration

    #+BEGIN_SRC emacs-lisp
      (use-package winner
        :ensure t
        :config
        (winner-mode t))
    #+END_SRC

*** ido
    =ido= has been kind to me since I started learning Emacs but learning =helm= might be better in the long term

    #+Begin_SRC emacs-lisp
      (use-package ido
        :disabled t
        :defer t
        :ensure t
        :config
        (ido-mode t)
        (ido-everywhere t)
        (setq ido-enable-flex-matching 1)
        (setq ido-show-dot-for-dired 1)

        ;; vertical ido display is better, like my taskbar
        (use-package ido-vertical-mode
              :ensure t
              :defer t
              :config
              (ido-vertical-mode t)
              (setq ido-vertical-show-count t))

        ;; flex matching is a must
        (use-package flx-ido
              :ensure t
              :defer t
              :config
              (flx-ido-mode t)
              (setq ido-enable-flex-matching t)
              (setq ido-use-faces nil))

        ;; smex is a great addition as well
        (use-package smex
          :ensure t
          :defer t
          :bind (("M-x" . smex)
    	     ("C-c C-c M-x" . execute-extended-command))
          :config
          (smex-initialize))
        )
    #+END_SRC

*** dired
    Directory management for Emacs

    #+BEGIN_SRC emacs-lisp
      (require 'dired-x) ;; Allows multi open marked files

      (setq dired-dwim-target t)

    #+END_SRC

** External Modes
*** guru
    Want to make sure I never hit those evil keys

    #+BEGIN_SRC emacs-lisp
      (use-package guru-mode
        :ensure t
        :config
        (guru-global-mode t)
      )
    #+END_SRC

*** nyan
    Love them kitty down there. Also this keeps things in perspective to have fun.

    #+BEGIN_SRC emacs-lisp
      (use-package nyan-mode
        :ensure t
        :config
        (nyan-mode t))
    #+END_SRC

*** org
    org-mode my buddy. This is filed under external modes since I download a new copy of org mode to be updated.

    Some basic setup

    #+BEGIN_SRC emacs-lisp
                  (use-package org
                    :ensure t
                    :config
                    ;; Setup
                    (add-to-list 'org-modules 'org-drill)

                    ;; Capture
                    (setq org-directory
                          (expand-file-name "~/Fakespace/nobody-library"))
                    (setq org-default-notes-file (concat org-directory "/capture.org")) ;; Personal org library

                    (setq org-journal-file (expand-file-name "journal.org" org-directory))
                    (setq org-review-file (expand-file-name "learning.org" org-directory))

                    (define-key global-map "\C-cc" 'org-capture)  ;; Use suggested key binding
                    (setq org-capture-templates
                          (list
                           (list "t" "Todo" 'entry
                                 (list 'file+headline org-default-notes-file "Todo")
                                 "* TODO %?\n %i\n %a")
                           (list "j" "Journal" 'entry
                                 (list 'file+datetree org-journal-file)
                                 "* %?\nEntered on %U\n %i\n %a")
                           (list "r" "Review/Remember" 'entry
                                 (list 'file+headline org-review-file "Learning Notes" "Review")
                                 "* %? :drill:\n :CREATED_ON: %T"))))

    #+END_SRC

*** projectile
    Must have a project finder when using a project.

    #+BEGIN_SRC emacs-lisp
      (use-package projectile
        :ensure t
        :config
        (projectile-global-mode t)
        (setq projectile-indexing-method 'native)
        )
    #+END_SRC

*** helm
    The revolutionary package to find

    #+BEGIN_SRC emacs-lisp
      (use-package async
        :ensure t)

      (use-package helm
        :ensure t
        :bind (("M-x" . helm-M-x)
               ("C-x C-f" . helm-find-files))
        :config
        (require 'helm-config)
        (setq helm-mode-fuzzy-match t)
        (setq helm-completion-in-region-fuzzy-match t)
        (helm-mode t))

      (use-package helm-projectile
        :ensure t
        :config
        (setq projectile-completion-system 'helm)
        (helm-projectile-on))

      (use-package helm-swoop
        :ensure t
        :bind (("M-i" . helm-swoop)
               ("C-c M-i" . helm-multi-swoop))
        :config
        (define-key helm-swoop-map (kbd "C-r") 'helm-previous-line)
        (define-key helm-swoop-map (kbd "C-s") 'helm-next-line)
        (define-key helm-multi-swoop-map (kbd "C-r") 'helm-previous-line)
        (define-key helm-multi-swoop-map (kbd "C-s") 'helm-next-line))

    #+END_SRC

*** autocomplete
    Autocomplete is a must have feature

    #+BEGIN_SRC emacs-lisp
      (use-package auto-complete
    	:ensure t
    	:config
    	(require 'auto-complete-config)
    	(ac-config-default)
    	(setq popup-use-optimized-column-computation nil))
    #+END_SRC

*** yasnippet
    Snippet system along with autocomplete is awesome

    #+BEGIN_SRC emacs-lisp
      (use-package yasnippet
      :ensure t
      :defer t)
    #+END_SRC

*** emmet
    I do a lot of HTML editing, YASnippet can do but emmet is better

    #+BEGIN_SRC emacs-lisp
      (use-package emmet-mode
        :ensure t
        :defer t)
    #+END_SRC

*** flycheck
    Syntax checking is very important

    #+BEGIN_SRC emacs-lisp
        (use-package flycheck
          :ensure t
          :defer t)
    #+END_SRC
*** flyspell
    Having a good spell checker is a must. I use =flyspell= although I have read issues about it

    #+BEGIN_SRC emacs-lisp
      (use-package flyspell
        :ensure t
        :defer t)
    #+END_SRC

*** js3
    A great mode for progressive nodejs

    #+BEGIN_SRC emacs-lisp
      (use-package js3-mode
        :ensure t
        :defer t)
    #+END_SRC

** Utility Modes
*** [[https://github.com/hayamiz/twittering-mode][twitter]]ing
    Integrating with emacs is very fun.

    #+BEGIN_SRC emacs-lisp
      (use-package twittering-mode
        :ensure t
        :defer t
        :init
        (setq twittering-auth-method 'xauth)
        :config
        (twittering-icon-mode t)
        (setq twittering-convert-fix-size 24))
    #+END_SRC

* Scripts
** projectile-init script
   This script runs .projectile-hook.el in each project root to ease development

   #+BEGIN_SRC emacs-lisp
     (defun fn/load-projectile-hook ()
       (interactive)
       (mapcar (lambda (project)
        (setq fn/current-project (expand-file-name project))
        (load
         (expand-file-name ".projectile-hook" fn/current-project)
         t))
 projectile-known-projects))
   #+END_SRC

** Open current buffer as root
   Taken from Mastering Emacs, this opens the current buffer as root via TRAMP

   #+BEGIN_SRC emacs-lisp
   #+END_SRC
* Reference
  - [[https://github.com/sachac/.emacs.d/blob/gh-pages/Sacha.org][Sacha Chua]]: I took her configuration as a base to make this org configuration
