# Database IDs for statuses
ISSUE_STATUS_NEW = 1
ISSUE_STATUS_REOPENED = 4
ISSUE_STATUS_DEV_DONE = 5
ISSUE_STATUS_TESTED = 7
ISSUE_STATUS_CANT_REPRODUCE = 12

TRACKER_BUG=1
TRACKER_SPRINT=TRACKER_FEATURE=2
TRACKER_TASK=TRACKER_SUPPORT=3

TRACKERS = {'bug':TRACKER_BUG,
            'feature':TRACKER_FEATURE,
            'task':TRACKER_TASK}

