language: emacs-lisp

env:
  matrix:
    - EMACS=emacs24

install:
  - if [ "$EMACS" = "emacs24" ]; then
        sudo apt-get install ghc cabal-install happy alex &&
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi

script:
  lsb_release -a && cabal update && cabal install --ghc-options=-O0 && cd elisp && make && PATH=../dist/build/structured-haskell-mode/:$PATH make test

notifications:
  email: false

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
